Create README.md
YaroslavAggressive/Intelligent-Placer pull request #1
Opened 2022-02-19 11:03 UTC by YaroslavAggressive

2022-02-19 19:32 UTC, sqrtyyy approved these changes

2022-02-23 22:42 UTC, PopeyeTheSailorsCat requested changes

2022-02-23 22:42 UTC, PopeyeTheSailorsCat commented on README.md
> +* Толщина предметов не превышает 3 см.
Больший смысл здесь будет иметь высота предмета не более 3 см.

2022-02-23 22:42 UTC, PopeyeTheSailorsCat commented on README.md
> +* Толщина маркера для изобращения многоугольника не превышает 3 мм.
Глянул тестовые изображения. Это очень неопределенное требование, тк у тебя на изображении пиксели(px), а не мм. Кроме того, с разной высоты (20-40 см) мм по разному перейдут в px. Кажется, что следует переделать толщину маркера через пиксели, кроме того, стоит выбрать нижнюю границу?

2022-02-23 22:42 UTC, PopeyeTheSailorsCat commented on README.md
> +* Красный леденец
Красный леденец? Не увидел его в Test kit

2022-02-23 22:42 UTC, PopeyeTheSailorsCat commented on README.md
> +# Intelligent-Placer
[Ссылка](https://stackoverflow.com/questions/14494747/how-to-add-images-to-readme-md-on-github)
Это в дальнейшем сильно упростит жизнь и чтение Readme

2022-02-26 13:06 UTC, YaroslavAggressive commented on README.md
> +* Красный леденец
Ошибочка вышла. После завершения README и перед загрузкой предметов на диск было принято решение заменить его на пауэрбанк Xiaomi, который на диске лежит. Данная неточность исправлена

2022-02-26 13:09 UTC, YaroslavAggressive commented on README.md
> +* Толщина предметов не превышает 3 см.
Согласен, формулировка не совсем корректная, изменил на твой более подходящий вариант

2022-02-26 13:21 UTC, sqrtyyy commented on Test Kit/.keep
> +
зачем пустой файл?

2022-02-26 13:23 UTC, YaroslavAggressive commented on README.md
> +# Intelligent-Placer
Добавлены изображения в README для упрощенного ознакомления с тестовым набором предметов

2022-02-26 13:25 UTC, YaroslavAggressive commented on Test Kit/.keep
> +
Потому что картинки пушились не через Git Bash, а вручную создавалась папка и в нее загружались изображения с гугл диска. Файл был создан 5 минут назад и уже удален

2022-02-26 15:22 UTC, YaroslavAggressive commented on README.md
> +* Толщина маркера для изобращения многоугольника не превышает 3 мм.
Замечание справедливое. Вообще говоря, на данный момент все фотографии были сделаны с высоты +- 40см (две офицерских линейки от стола), поэтому может нижняя граница пока и не нужна. В целом при детальном рассмотрении многоугольников с пиксельным масштабом сделал вывод, что их граница находится в пределах 5-7 пикселей. Думаю пока при добавлении новых тестовых примеров соблюдать данные условия их создания, соответствующие исправления в README внесены

2022-02-26 16:43 UTC, Maltseva-Anastasia commented
В целом, отличная работа! Требования к входным/выходным данным хорошо продуманы.
Успехов в дальнейшей реализации задуманного!

2022-02-26 20:50 UTC, PopeyeTheSailorsCat approved these changes

2022-02-26 20:57 UTC, YaroslavAggressive commented on README.md
> +* Предметы отличаются по оттенку.
Справедливое замечание, добавил несколько тестовых примеров для кошелька и паспорта. Планирую пока оставить эти два примера в тестовом наборе, так как вся фишка в том, что в некоторых местах у паспорта видна желтая внутренность, за счет чего его предполагается отличать от кошелька. Но, возможно, это лучше еще раз обсудить с заказчиком (преподавателем)

2022-02-26 21:27 UTC, YaroslavAggressive commented on README.md
> +* Предметы отличаются по оттенку.
Если замечаний больше нет, буду благодарен, если сделаешь approve changes, чтобы можно было закрыть pull request

2022-02-27 09:52 UTC, Maltseva-Anastasia approved these changes

2022-02-27 10:07 UTC, merged